// Code generated by go-swagger; DO NOT EDIT.

package operation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCacertsLabelledParams creates a new CacertsLabelledParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCacertsLabelledParams() *CacertsLabelledParams {
	return &CacertsLabelledParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCacertsLabelledParamsWithTimeout creates a new CacertsLabelledParams object
// with the ability to set a timeout on a request.
func NewCacertsLabelledParamsWithTimeout(timeout time.Duration) *CacertsLabelledParams {
	return &CacertsLabelledParams{
		timeout: timeout,
	}
}

// NewCacertsLabelledParamsWithContext creates a new CacertsLabelledParams object
// with the ability to set a context for a request.
func NewCacertsLabelledParamsWithContext(ctx context.Context) *CacertsLabelledParams {
	return &CacertsLabelledParams{
		Context: ctx,
	}
}

// NewCacertsLabelledParamsWithHTTPClient creates a new CacertsLabelledParams object
// with the ability to set a custom HTTPClient for a request.
func NewCacertsLabelledParamsWithHTTPClient(client *http.Client) *CacertsLabelledParams {
	return &CacertsLabelledParams{
		HTTPClient: client,
	}
}

/* CacertsLabelledParams contains all the parameters to send to the API endpoint
   for the cacerts labelled operation.

   Typically these are written to a http.Request.
*/
type CacertsLabelledParams struct {

	/* Label.

	   CA Additional Information
	*/
	Label string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the cacerts labelled params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CacertsLabelledParams) WithDefaults() *CacertsLabelledParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the cacerts labelled params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CacertsLabelledParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the cacerts labelled params
func (o *CacertsLabelledParams) WithTimeout(timeout time.Duration) *CacertsLabelledParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cacerts labelled params
func (o *CacertsLabelledParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cacerts labelled params
func (o *CacertsLabelledParams) WithContext(ctx context.Context) *CacertsLabelledParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cacerts labelled params
func (o *CacertsLabelledParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cacerts labelled params
func (o *CacertsLabelledParams) WithHTTPClient(client *http.Client) *CacertsLabelledParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cacerts labelled params
func (o *CacertsLabelledParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLabel adds the label to the cacerts labelled params
func (o *CacertsLabelledParams) WithLabel(label string) *CacertsLabelledParams {
	o.SetLabel(label)
	return o
}

// SetLabel adds the label to the cacerts labelled params
func (o *CacertsLabelledParams) SetLabel(label string) {
	o.Label = label
}

// WriteToRequest writes these params to a swagger request
func (o *CacertsLabelledParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param label
	if err := r.SetPathParam("label", o.Label); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
