// Code generated by go-swagger; DO NOT EDIT.

package operation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SimpleenrollReader is a Reader for the Simpleenroll structure.
type SimpleenrollReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SimpleenrollReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSimpleenrollOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSimpleenrollBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewSimpleenrollUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSimpleenrollInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSimpleenrollOK creates a SimpleenrollOK with default headers values
func NewSimpleenrollOK() *SimpleenrollOK {
	var (
		// initialize headers with default values
		contentTransferEncodingDefault = string("base64")

		contentTypeDefault = string("application/pkcs7-mime")
	)

	return &SimpleenrollOK{

		ContentTransferEncoding: contentTransferEncodingDefault,
		ContentType:             contentTypeDefault,
	}
}

/* SimpleenrollOK describes a response with status code 200, with default header values.

successful operation
*/
type SimpleenrollOK struct {
	ContentTransferEncoding string
	ContentType             string

	Payload string
}

func (o *SimpleenrollOK) Error() string {
	return fmt.Sprintf("[POST /simpleenroll][%d] simpleenrollOK  %+v", 200, o.Payload)
}
func (o *SimpleenrollOK) GetPayload() string {
	return o.Payload
}

func (o *SimpleenrollOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Content-Transfer-Encoding
	hdrContentTransferEncoding := response.GetHeader("Content-Transfer-Encoding")

	if hdrContentTransferEncoding != "" {
		o.ContentTransferEncoding = hdrContentTransferEncoding
	}

	// hydrates response header Content-Type
	hdrContentType := response.GetHeader("Content-Type")

	if hdrContentType != "" {
		o.ContentType = hdrContentType
	}

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSimpleenrollBadRequest creates a SimpleenrollBadRequest with default headers values
func NewSimpleenrollBadRequest() *SimpleenrollBadRequest {
	return &SimpleenrollBadRequest{}
}

/* SimpleenrollBadRequest describes a response with status code 400, with default header values.

invalid request
*/
type SimpleenrollBadRequest struct {
	Payload string
}

func (o *SimpleenrollBadRequest) Error() string {
	return fmt.Sprintf("[POST /simpleenroll][%d] simpleenrollBadRequest  %+v", 400, o.Payload)
}
func (o *SimpleenrollBadRequest) GetPayload() string {
	return o.Payload
}

func (o *SimpleenrollBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSimpleenrollUnauthorized creates a SimpleenrollUnauthorized with default headers values
func NewSimpleenrollUnauthorized() *SimpleenrollUnauthorized {
	return &SimpleenrollUnauthorized{}
}

/* SimpleenrollUnauthorized describes a response with status code 401, with default header values.

Authentication information is missing or invalid
*/
type SimpleenrollUnauthorized struct {
	WWWAuthenticate string
}

func (o *SimpleenrollUnauthorized) Error() string {
	return fmt.Sprintf("[POST /simpleenroll][%d] simpleenrollUnauthorized ", 401)
}

func (o *SimpleenrollUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header WWW_Authenticate
	hdrWWWAuthenticate := response.GetHeader("WWW_Authenticate")

	if hdrWWWAuthenticate != "" {
		o.WWWAuthenticate = hdrWWWAuthenticate
	}

	return nil
}

// NewSimpleenrollInternalServerError creates a SimpleenrollInternalServerError with default headers values
func NewSimpleenrollInternalServerError() *SimpleenrollInternalServerError {
	return &SimpleenrollInternalServerError{}
}

/* SimpleenrollInternalServerError describes a response with status code 500, with default header values.

something went wrong
*/
type SimpleenrollInternalServerError struct {
	Payload string
}

func (o *SimpleenrollInternalServerError) Error() string {
	return fmt.Sprintf("[POST /simpleenroll][%d] simpleenrollInternalServerError  %+v", 500, o.Payload)
}
func (o *SimpleenrollInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *SimpleenrollInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
