// Code generated by go-swagger; DO NOT EDIT.

package operation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSimplereenrollLabelledParams creates a new SimplereenrollLabelledParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSimplereenrollLabelledParams() *SimplereenrollLabelledParams {
	return &SimplereenrollLabelledParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSimplereenrollLabelledParamsWithTimeout creates a new SimplereenrollLabelledParams object
// with the ability to set a timeout on a request.
func NewSimplereenrollLabelledParamsWithTimeout(timeout time.Duration) *SimplereenrollLabelledParams {
	return &SimplereenrollLabelledParams{
		timeout: timeout,
	}
}

// NewSimplereenrollLabelledParamsWithContext creates a new SimplereenrollLabelledParams object
// with the ability to set a context for a request.
func NewSimplereenrollLabelledParamsWithContext(ctx context.Context) *SimplereenrollLabelledParams {
	return &SimplereenrollLabelledParams{
		Context: ctx,
	}
}

// NewSimplereenrollLabelledParamsWithHTTPClient creates a new SimplereenrollLabelledParams object
// with the ability to set a custom HTTPClient for a request.
func NewSimplereenrollLabelledParamsWithHTTPClient(client *http.Client) *SimplereenrollLabelledParams {
	return &SimplereenrollLabelledParams{
		HTTPClient: client,
	}
}

/* SimplereenrollLabelledParams contains all the parameters to send to the API endpoint
   for the simplereenroll labelled operation.

   Typically these are written to a http.Request.
*/
type SimplereenrollLabelledParams struct {

	/* Certrequest.

	   PKCS10 certificate request (DER format, base64 encoded)
	*/
	Certrequest string

	/* Label.

	   CA Additional Information
	*/
	Label string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the simplereenroll labelled params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SimplereenrollLabelledParams) WithDefaults() *SimplereenrollLabelledParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the simplereenroll labelled params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SimplereenrollLabelledParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the simplereenroll labelled params
func (o *SimplereenrollLabelledParams) WithTimeout(timeout time.Duration) *SimplereenrollLabelledParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the simplereenroll labelled params
func (o *SimplereenrollLabelledParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the simplereenroll labelled params
func (o *SimplereenrollLabelledParams) WithContext(ctx context.Context) *SimplereenrollLabelledParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the simplereenroll labelled params
func (o *SimplereenrollLabelledParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the simplereenroll labelled params
func (o *SimplereenrollLabelledParams) WithHTTPClient(client *http.Client) *SimplereenrollLabelledParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the simplereenroll labelled params
func (o *SimplereenrollLabelledParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCertrequest adds the certrequest to the simplereenroll labelled params
func (o *SimplereenrollLabelledParams) WithCertrequest(certrequest string) *SimplereenrollLabelledParams {
	o.SetCertrequest(certrequest)
	return o
}

// SetCertrequest adds the certrequest to the simplereenroll labelled params
func (o *SimplereenrollLabelledParams) SetCertrequest(certrequest string) {
	o.Certrequest = certrequest
}

// WithLabel adds the label to the simplereenroll labelled params
func (o *SimplereenrollLabelledParams) WithLabel(label string) *SimplereenrollLabelledParams {
	o.SetLabel(label)
	return o
}

// SetLabel adds the label to the simplereenroll labelled params
func (o *SimplereenrollLabelledParams) SetLabel(label string) {
	o.Label = label
}

// WriteToRequest writes these params to a swagger request
func (o *SimplereenrollLabelledParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Certrequest); err != nil {
		return err
	}

	// path param label
	if err := r.SetPathParam("label", o.Label); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
