// Code generated by go-swagger; DO NOT EDIT.

package operation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSimpleenrollLabelledParams creates a new SimpleenrollLabelledParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSimpleenrollLabelledParams() *SimpleenrollLabelledParams {
	return &SimpleenrollLabelledParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSimpleenrollLabelledParamsWithTimeout creates a new SimpleenrollLabelledParams object
// with the ability to set a timeout on a request.
func NewSimpleenrollLabelledParamsWithTimeout(timeout time.Duration) *SimpleenrollLabelledParams {
	return &SimpleenrollLabelledParams{
		timeout: timeout,
	}
}

// NewSimpleenrollLabelledParamsWithContext creates a new SimpleenrollLabelledParams object
// with the ability to set a context for a request.
func NewSimpleenrollLabelledParamsWithContext(ctx context.Context) *SimpleenrollLabelledParams {
	return &SimpleenrollLabelledParams{
		Context: ctx,
	}
}

// NewSimpleenrollLabelledParamsWithHTTPClient creates a new SimpleenrollLabelledParams object
// with the ability to set a custom HTTPClient for a request.
func NewSimpleenrollLabelledParamsWithHTTPClient(client *http.Client) *SimpleenrollLabelledParams {
	return &SimpleenrollLabelledParams{
		HTTPClient: client,
	}
}

/* SimpleenrollLabelledParams contains all the parameters to send to the API endpoint
   for the simpleenroll labelled operation.

   Typically these are written to a http.Request.
*/
type SimpleenrollLabelledParams struct {

	/* Certrequest.

	   PKCS10 certificate request (DER format, base64 encoded)
	*/
	Certrequest string

	/* Label.

	   CA Additional Information
	*/
	Label string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the simpleenroll labelled params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SimpleenrollLabelledParams) WithDefaults() *SimpleenrollLabelledParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the simpleenroll labelled params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SimpleenrollLabelledParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the simpleenroll labelled params
func (o *SimpleenrollLabelledParams) WithTimeout(timeout time.Duration) *SimpleenrollLabelledParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the simpleenroll labelled params
func (o *SimpleenrollLabelledParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the simpleenroll labelled params
func (o *SimpleenrollLabelledParams) WithContext(ctx context.Context) *SimpleenrollLabelledParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the simpleenroll labelled params
func (o *SimpleenrollLabelledParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the simpleenroll labelled params
func (o *SimpleenrollLabelledParams) WithHTTPClient(client *http.Client) *SimpleenrollLabelledParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the simpleenroll labelled params
func (o *SimpleenrollLabelledParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCertrequest adds the certrequest to the simpleenroll labelled params
func (o *SimpleenrollLabelledParams) WithCertrequest(certrequest string) *SimpleenrollLabelledParams {
	o.SetCertrequest(certrequest)
	return o
}

// SetCertrequest adds the certrequest to the simpleenroll labelled params
func (o *SimpleenrollLabelledParams) SetCertrequest(certrequest string) {
	o.Certrequest = certrequest
}

// WithLabel adds the label to the simpleenroll labelled params
func (o *SimpleenrollLabelledParams) WithLabel(label string) *SimpleenrollLabelledParams {
	o.SetLabel(label)
	return o
}

// SetLabel adds the label to the simpleenroll labelled params
func (o *SimpleenrollLabelledParams) SetLabel(label string) {
	o.Label = label
}

// WriteToRequest writes these params to a swagger request
func (o *SimpleenrollLabelledParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Certrequest); err != nil {
		return err
	}

	// path param label
	if err := r.SetPathParam("label", o.Label); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
